[package]
name = "metadata-validator"
version = "0.28.2"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version = "4.5.53", features = ["derive"] }
libloot = "0.28.2"
tempfile = "3"

[[bin]]
name = "metadata_validator"
path = "src/main.rs"
