
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.loot]
url = "https://raw.githubusercontent.com/loot/supply-chain/main/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.ortham]
url = "https://raw.githubusercontent.com/Ortham/supply-chain/main/audits.toml"

[[exemptions.aho-corasick]]
version = "1.1.3"
criteria = "safe-to-deploy"

[[exemptions.anstream]]
version = "0.6.19"
criteria = "safe-to-deploy"

[[exemptions.anstyle]]
version = "1.0.11"
criteria = "safe-to-deploy"

[[exemptions.anstyle-parse]]
version = "0.2.7"
criteria = "safe-to-deploy"

[[exemptions.anstyle-query]]
version = "1.1.3"
criteria = "safe-to-deploy"

[[exemptions.anstyle-wincon]]
version = "3.0.9"
criteria = "safe-to-deploy"

[[exemptions.anyhow]]
version = "1.0.98"
criteria = "safe-to-deploy"

[[exemptions.clap]]
version = "4.5.40"
criteria = "safe-to-deploy"

[[exemptions.clap_builder]]
version = "4.5.40"
criteria = "safe-to-deploy"

[[exemptions.clap_derive]]
version = "4.5.40"
criteria = "safe-to-deploy"

[[exemptions.clap_lex]]
version = "0.7.5"
criteria = "safe-to-deploy"

[[exemptions.colorchoice]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.const-random]]
version = "0.1.18"
criteria = "safe-to-deploy"

[[exemptions.const-random-macro]]
version = "0.1.16"
criteria = "safe-to-deploy"

[[exemptions.crc32fast]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-deque]]
version = "0.8.6"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-epoch]]
version = "0.9.18"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-utils]]
version = "0.8.21"
criteria = "safe-to-deploy"

[[exemptions.dataview]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.derive_pod]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.dirs]]
version = "6.0.0"
criteria = "safe-to-deploy"

[[exemptions.dirs-sys]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.dlv-list]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.errno]]
version = "0.3.12"
criteria = "safe-to-deploy"
suggest = false
notes = "At time of review this was only built if targeting WASI, which is not an intended target."

[[exemptions.fixedbitset]]
version = "0.5.7"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.14.5"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.15.4"
criteria = "safe-to-deploy"

[[exemptions.hashlink]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.is_terminal_polyfill]]
version = "1.70.1"
criteria = "safe-to-deploy"

[[exemptions.keyvalues-parser]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.libredox]]
version = "0.1.3"
criteria = "safe-to-deploy"
suggest = false
notes = "At time of review this was only built if targeting Redox, which is not an intended target."

[[exemptions.linux-raw-sys]]
version = "0.11.0"
criteria = "safe-to-deploy"
suggest = false
notes = "At time of review this was only built if targeting WASI, which is not an intended target."

[[exemptions.memchr]]
version = "2.7.5"
criteria = "safe-to-deploy"

[[exemptions.no-std-compat]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.nom]]
version = "8.0.0"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.21.3"
criteria = "safe-to-deploy"

[[exemptions.once_cell_polyfill]]
version = "1.70.1"
criteria = "safe-to-deploy"

[[exemptions.ordered-float]]
version = "5.0.0"
criteria = "safe-to-deploy"

[[exemptions.ordered-multimap]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.pelite]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.pelite-macros]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.pest]]
version = "2.8.0"
criteria = "safe-to-deploy"

[[exemptions.petgraph]]
version = "0.8.2"
criteria = "safe-to-deploy"

[[exemptions.r-efi]]
version = "5.2.0"
criteria = "safe-to-deploy"
suggest = false
notes = "At time of review this was only built if targeting UEFI, which is not an intended target."

[[exemptions.redox_users]]
version = "0.5.0"
criteria = "safe-to-deploy"
suggest = false
notes = "At time of review this was only built if targeting Redox, which is not an intended target."

[[exemptions.regex]]
version = "1.11.1"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.4.9"
criteria = "safe-to-deploy"

[[exemptions.regress]]
version = "0.10.4"
criteria = "safe-to-deploy"

[[exemptions.rust-ini]]
version = "0.21.1"
criteria = "safe-to-deploy"

[[exemptions.rustix]]
version = "1.1.3"
criteria = "safe-to-deploy"
suggest = false
notes = "At time of review this was only built if targeting WASI, which is not an intended target."

[[exemptions.saphyr]]
version = "0.0.6"
criteria = "safe-to-deploy"

[[exemptions.saphyr-parser]]
version = "0.0.6"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.102"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.20.0"
criteria = "safe-to-deploy"

[[exemptions.thiserror]]
version = "2.0.12"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "2.0.12"
criteria = "safe-to-deploy"

[[exemptions.tiny-keccak]]
version = "2.0.2"
criteria = "safe-to-deploy"

[[exemptions.trim-in-place]]
version = "0.1.7"
criteria = "safe-to-deploy"

[[exemptions.ucd-trie]]
version = "0.1.7"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.1+wasi-snapshot-preview1"
criteria = "safe-to-deploy"
suggest = false
notes = "At time of review this was only built if targeting WASI, which is not an intended target."

[[exemptions.wasi]]
version = "0.14.2+wasi-0.2.4"
criteria = "safe-to-deploy"
suggest = false
notes = "At time of review this was only built if targeting WASI, which is not an intended target."

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"
